from enum import Enum


class GameResult(Enum):
    WHITE_WON_BY_CHECKMATE = 1
    BLACK_WON_BY_CHECKMATE = -1
    WHITE_WON_BY_RESIGNATION = 2
    BLACK_WON_BY_RESIGNATION = -2
    WHITE_WON_BY_TIMEOUT = 3
    BLACK_WON_BY_TIMEOUT = -3
    DRAW_BY_STALEMATE = 4
    DRAW_BY_INSUFFICIENT_MATERIAL = 5
    DRAW_BY_THREEFOLD_REPETITION = 6
